# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sbom-analysis',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/sbom-analysis',
                'lib_path': 'sbom_analysis'},
  'syms': {'sbom_analysis.core': {'sbom_analysis.core.show_metadata': ('core.html#show_metadata', 'sbom_analysis/core.py')}}}
