project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - sidebar:sbom_analysis
      - sidebar:tool_analysis
      - sidebar:other_investigations
  
  sidebar:    
    - id: sbom_analysis
      title: "SBOMs"
      collapse-level: 2
      border: true
      style: "docked"      
      search: true
      contents:
        - sbom-basic/00_core.ipynb
        - sbom-basic/01_spdx_example.ipynb
        - sbom-basic/minimum_elements.ipynb        
        - section: "Microsoft SBOMTool"
          contents:        
          - text: "General Analysis"
            file: sbom-basic/microsoft_sbomtool_overview.ipynb
          - section: "[Case Studies]"
            contents:
            - text: "•repo:ndcrane/frameworks-getting-started"
              file: sbom-basic/02_frameworks_getting_started.ipynb
            - text: "•repo:ggerganov/llama.cpp"  
              file: sbom-basic/03_llama.cpp.ipynb
            - text: "•repo:TheBloke/text-generation-webui"  
              file: sbom-basic/04_hugging_face.ipynb
            - text: "•repo:numpy/numpy"  
              file: sbom-basic/05_numpy.ipynb
            - text: "•repo:pytorch/pytorch"  
              file: sbom-basic/06_pytorch.ipynb
    - id: tool_analysis
      title: "Tool Analysis"    
      collapse-level: 4
      border: true
      style: "docked"
      search: true      
      contents:
        - text: "Getting Started"
          file: tool_analysis/introduction.ipynb
        - text: "Overall Analysis"
          file: tool_analysis/tools_overall_analysis.qmd
        - section: "[Case Studies]"
          contents:
            - section: "• repo:pytorch/pytorch"
              contents:
              - text: "Overall Analysis"
                file: tool_analysis/cs1/overall_analysis.ipynb
              - section: "Analysis by Tools" 
                contents:
                - text: "Syft"
                  file: tool_analysis/cs1/syft.ipynb
                - text: "Trivy"
                  file: tool_analysis/cs1/trivy.ipynb
                - text: "Tern"
                  file: tool_analysis/cs1/tern.ipynb  
                - text: "Microsoft SBOM Tool"
                  file: tool_analysis/cs1/sbomtool.ipynb  
                - text: "GitHub Dependency Graph"
                  file: tool_analysis/cs1/gssbom.ipynb  
                - text: "sbom4python"
                  file: tool_analysis/cs1/sbom4python.ipynb  
                - text: "Fossa"
                  file: tool_analysis/cs1/fossa.ipynb                                  
                - text: "bom"
                  file: tool_analysis/cs1/bom.ipynb
                - text: "sbom4python"
                  file: tool_analysis/cs1/sbom4python.ipynb
                  

    - id: other_investigations
      title: "AI Specifications"      
      style: "docked"
      search: true
      contents:        
        - text: "Hugging Face Model Cards"
          file: ai_specifications/hugging_face_model_cards.ipynb
        #- text: "Hugging Face Dataset Cards"
        #  file: None
        - text: "SPDX3 AIPackage"
          file: ai_specifications/SPDX3_AIPackage.ipynb
        #- text: "DVC Model Register"
        #  file: None

metadata-files: [nbdev.yml]